services:

  mitmproxy:
    build: ./mitm-proxy
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - guardian

  nginx:
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - mitmproxy

  guardian:
    build: ./guardian
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
