services:
  node-api:
    build: ./node-api
    ports:
      - "3000:3000"

  mitmproxy:
    build: ./mitm-proxy
    ports:
      - "8080:8080"
    depends_on:
      - node-api

  nginx:
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - mitmproxy

  guardian:
    build: ./guardian
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
